DATA SEGMENT
		PD DB "PELINDROME. $ "
		NPD DB "NOT PELINDROME. $"
		STR1 DB 'J','E','E','L'
DATA ENDS

STAC SEGMENT STACK
			DB 40 DUP(0)
	STACK_TOP LABEL WORD
STAC ENDS

COD SEGMENT
ASSUME cs:COD,ss:STAC,ds:DATA

START: MOV AX,DATA
		MOV DS,AX
		MOV AX,STAC
		MOV SS,AX
		LEA SP,STACK_TOP
		CALL CHECKP
		INT 3H
CHECKP PROC NEAR
			PUSHF
			PUSH AX
			PUSH BX
			PUSH CX
			LEA SI,STR1
			MOV CX,0002H
			LEA DI,STR1+3
			
	NEXT:	
			MOV AL,BYTE PTR[SI]
			MOV BL,BYTE PTR[DI]
			CMP AL,BL
			MOV AX,09H
			JNZ SKIP
			INC SI
			DEC DI
			LOOP NEXT
			
			LEA DX,PD
			JMP OVER
	SKIP:	LEA DX,NPD
	OVER:   INT 21H
			POP CX
			POP BX
			POP AX
			POPF
			RET
CHECKP ENDP

COD ENDS
END START			